config/routes.rb
Rails.application.routes.draw do

  get 'commissions/new'
  get 'commissions/create'
  get 'commissions/destroy' 
  
  get 'about/index'
    
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }  
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "requests#index"
  
  resources :requests do
    resource :commissions, only: [:new, :create, :destroy]
  end
  
  get 'requests/about'

  resources :artists do
    resource :reviews, only: [:new, :create, :destroy]
  end
  
  get 'adm', to: 'admins#index', :as => :admin_view
  get 'adm/ban/:id', to: 'admins#unartist_user', :via => :get, :as => :admin_unartist_user
  get 'adm/unban/:id', to: 'admins#makeartist_user', :via => :get, :as => :admin_makeartist_user
  get 'adm/admin/:id', to: 'admins#admin_user', :via => :get, :as => :admin_admin_user
  get 'adm/unadmin/:id', to: 'admins#unadmin_user', :via => :get, :as => :admin_unadmin_user
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :reviews
  has_many :commissions
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  before_action :set_artist, only: %i[ show edit update destroy ]

  # GET /artists or /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1 or /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists or /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: "Artist was successfully created." }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1 or /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: "Artist was successfully updated." }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1 or /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: "Artist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artist_params
      params.require(:artist).permit(:name, :genre, :about)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: artist) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
        <% artist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.select :genre, :collection => %w[Manga Western Paint Digital] %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Elenco Artisti</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Genre</th>
      <th>About</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.genre %></td>
        <td><%= artist.about %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p>
  <%= link_to 'Diventa un\'Artista', new_artist_path %>
  <br>
  <%= link_to 'Elenco Requests', requests_path %>
  <br>
</p>
<p><br></p>
<br>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @artist.genre %>
</p>

<p>
  <strong>About:</strong>
  <%= @artist.about %>
</p>
<p>
<div><h3>Recensioni</h3></div>
<div>
  <% if @artist.reviews.empty? %>
  <p>Questo artista non ha ancora ricevuto recensioni...</p>
<% else %>
  <p>
    <% @artist.reviews.each do |r| %>
      <strong><%= r.vote%>:</strong>
      <%= r.comments %>
      <br>
    <% end %>
  </p>
<% end %>
</div>
</p>
<br>
<ul>
  <li><%= link_to 'Edit', edit_artist_path(@artist) %></li>
  <li><%= link_to 'Aggiungi Recensione', new_artist_reviews_path(@artist) %></li>
  <li><%= link_to 'Back', artists_path %></li>
</ul>