config/routes.rb
Rails.application.routes.draw do

  get 'commissions/new'
  get 'commissions/create'
  get 'commissions/destroy' 
  
  get 'about/index'
    
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }  
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "requests#index"
  
  resources :requests do
    resource :commissions, only: [:new, :create, :destroy]
  end
  
  get 'requests/about'

  resources :artists do
    resource :reviews, only: [:new, :create, :destroy]
  end
  
  get 'adm', to: 'admins#index', :as => :admin_view
  get 'adm/ban/:id', to: 'admins#unartist_user', :via => :get, :as => :admin_unartist_user
  get 'adm/unban/:id', to: 'admins#makeartist_user', :via => :get, :as => :admin_makeartist_user
  get 'adm/admin/:id', to: 'admins#admin_user', :via => :get, :as => :admin_admin_user
  get 'adm/unadmin/:id', to: 'admins#unadmin_user', :via => :get, :as => :admin_unadmin_user
end

app/views/admins/index.html.erb
<style>
table, th, td {
  border: 1px solid blue;
}
</style>
<table>
  <tr>
    <th> Email </th>
    <th> Artist </th>
    <th> Admin </th>

    <th> Artist Button </th>
    <th> Admin Button </th>

  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.is_artist? %></td>
      <td><%= user.is_admin? %></td>
      <td><% if user.is_artist? %>
        <%= link_to "Remove Artist", admin_unartist_user_path(user.id), method: :get, data: { confirm: " Sei sicuro? " } %>
        <%else%>
          <%= link_to "Remove Artist", admin_makeartist_user_path(user.id), method: :get, data: { confirm: " Sei sicuro? " } %>
          <%end%>
      </td>
      <td>
        <% if user.is_admin? %>
          <%= link_to "Remove Admin", admin_unadmin_user_path(user.id), method: :get, data: { confirm: " Sei sicuro" } %>
          <%else%>
            <%= link_to "Make Admin", admin_admin_user_path(user.id), method: :get, data: { confirm: " Sei sicuro? " } %>
          <%end%>
      </td>
    </tr>
</table>