config/routes.rb
Rails.application.routes.draw do

  get 'commissions/new'
  get 'commissions/create'
  get 'commissions/destroy' 
  
  get 'about/index'
    
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }  
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "requests#index"
  
  resources :requests do
    resource :commissions, only: [:new, :create, :destroy]
  end
  
  get 'requests/about'

  resources :artists do
    resource :reviews, only: [:new, :create, :destroy]
  end
  
  get 'adm', to: 'admins#index', :as => :admin_view
  get 'adm/ban/:id', to: 'admins#unartist_user', :via => :get, :as => :admin_unartist_user
  get 'adm/unban/:id', to: 'admins#makeartist_user', :via => :get, :as => :admin_makeartist_user
  get 'adm/admin/:id', to: 'admins#admin_user', :via => :get, :as => :admin_admin_user
  get 'adm/unadmin/:id', to: 'admins#unadmin_user', :via => :get, :as => :admin_unadmin_user
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_many :commissions
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  require 'wikipedia'

  before_action :set_request, only: %i[ show edit update destroy ]
  before_action :require_permission, only: :edit

  def require_permission
    if current_user != Request.find(params[:id]).user
      flash.alert = "You are not allowed to edit the Request"
     
    end
  end
 
  # GET /requests or /requests.json
  def index
    if params[:genre]
      @requests = Request.where(:genre => params[:genre])
    else
      @requests = Request.all
    end
  end

  # GET /requests/1 or /requests/1.json
  def show

  end

  # GET /requests/new
  def new
    @request = Request.new
    @request = current_user.requests.build
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
  end

  # POST /requests or /requests.json
  def create
    @request = Request.new(request_params)
    @request = current_user.requests.build(request_params)
    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: "Request was successfully created." }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1 or /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: "Request was successfully updated." }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1 or /requests/1.json
  def destroy
    authorize! :destroy, Request, :message => "Non sei autorizzato"

    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: "Request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def requests_params
      params.require(:request).permit(:your_requests_params, :user_id)
    end
  
    def set_request
      if[:id] != "about"
        @request = Request.find(params[:id])
      end
    end

    # Only allow a list of trusted parameters through.
    def request_params
      params.require(:request).permit(:title, :genre, :tag1, :tag2, :reference, :description)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_with(model: request) do |form| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
        <% request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.select :genre, :collection => %w[Manga Western Paint Digital] %>
  </div>

  <div class="field">
    <%= form.label :tag1 %>
    <%= form.select :tag1, :collection => %w[Traditional Fanart Vectorial] %>
  </div>

  <div class="field">
    <%= form.label :tag2 %>
    <%= form.select :tag2, :collection => %w[Action Horror Romance Ecchi Seinen Yuri Yaoi] %>
  </div>

  <div class="field">
    <%= form.label :reference %>
    <%= form.text_field :reference %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
  <style>
   table, th, td {
     border: 1px solid black;
  }
</style>

<p id="notice"><%= notice %></p>


<h1>Requests List</h1>
<br>
<div>
  <h4> Cerca per Genere</h4>
  <ul>
      <li><%= link_to "Western", requests_path(:genre=>"Western") %></li>
      <li><%= link_to "Manga", requests_path(:genre=>"Manga") %></li>
      <li><%= link_to "Paint", requests_path(:genre=>"Paint") %></li>
      <li><%= link_to "Digital", requests_path(:genre=>"Digital") %></li>
    </ul>
</div>

<br>
<table style="width:100%">
    <tr>
      <th>Title</th>
      <th>Genre</th>
      
      <th colspan="3"></th>
    </tr>

    <% @requests.each do |request| %>
      
      <tr>
        <td><%= request.title %></td>
        <td><%= request.genre %></td>
        <td><table style="width:100%">
          <td><%= link_to 'Show', request %></td>
          <td><%= link_to 'Edit', edit_request_path(request) %></td>
          <td><% if can? :destroy, Request %>
            <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%else%>
            <td><s>Destroy</s></td>
            <% end %></td>
          </table>
        </td>  
      </tr>
    <% end %>
</table>
    Se hai bisogno di un aiuto, consulta la <%= link_to 'guida', about_index_path(:genre=>"Western comic")%>
<br>

<br>
<h2>Collabora con noi</h2>
<%= link_to 'Aggiungi una Richiesta', new_request_path %>
<br>
<%= link_to 'Diventa un\'Artista', new_artist_path %>
<br>
<%= link_to 'Elenco Artisti', artists_path %>
<br>

<br>
<br><br>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @request.title %>
</p>

<p>
  <strong>Requester:</strong>
  <%= @request.user_id %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @request.genre %>
</p>

<p>
  <strong>Tag1:</strong>
  <%= @request.tag1 %>
</p>

<p>
  <strong>Tag2:</strong>
  <%= @request.tag2 %>
</p>

<p>
  <strong>Reference:</strong>
  <%= link_to(@request.reference,@request.reference) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @request.description %>
</p>

<br>
<p>
<h3>Proposte di Commissione</h3>
<% if @request.commissions.empty? %>
  <p></p>
<% else %>
  <p>
    <% @request.commissions.each do |r| %>
      <strong><%= Artist.find(r.artist_id).name%>:</strong>
      <%= r.prize%>€,  
      <%= r.details %>
      <br>
    <% end %>
  </p>
<% end %>
</p>



<br><br><br>

<h2> Aggiungi proposta di Commissione </h2>
<%if can? :create, Commission %>
    <%= form_with model: [ @request, @request.commissions.build ] do |form| %>
      <p>
        <strong><%= form.label :details, "Dettagli" %></strong><br>
        <%= form.text_area :details %>
      </p>

      <p>
        <strong><%= form.label :prize, "Prezzo" %></strong><br>
        <%= form.number_field :prize, in: 10..100.0, step: 0.5 %>
      </p>

      <p>
        <strong><%= form.label :artist %></strong><br>
        <%= form.collection_select :artist, Artist.all, :id, :name %>
      </p>
      <p>
        <%= form.submit "Aggiungi proposta" %>
        </p>
    <% end %>
<%else%>
  <u>Non sei un Artista, non puoi fare proposte per una commissione.</u>
<% end %>

<br><br>
<%= link_to 'Edit', edit_request_path(@request) %>
<%= link_to 'Back', requests_path %>
<br>