config/routes.rb
Rails.application.routes.draw do

  get 'commissions/new'
  get 'commissions/create'
  get 'commissions/destroy' 
  
  get 'about/index'
    
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }  
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "requests#index"
  
  resources :requests do
    resource :commissions, only: [:new, :create, :destroy]
  end
  
  get 'requests/about'

  resources :artists do
    resource :reviews, only: [:new, :create, :destroy]
  end
  
  get 'adm', to: 'admins#index', :as => :admin_view
  get 'adm/ban/:id', to: 'admins#unartist_user', :via => :get, :as => :admin_unartist_user
  get 'adm/unban/:id', to: 'admins#makeartist_user', :via => :get, :as => :admin_makeartist_user
  get 'adm/admin/:id', to: 'admins#admin_user', :via => :get, :as => :admin_admin_user
  get 'adm/unadmin/:id', to: 'admins#unadmin_user', :via => :get, :as => :admin_unadmin_user
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
  end

  def create
    id_artist = params[:artist_id]
    @artist = Artist.find(id_artist)
    @review = @artist.reviews.create!(:vote =>params[:review][:vote], :comments => params[:review][:comments])
    redirect_to artists_path
  end

  def destroy
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/create.html.haml
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/destroy.html.haml
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/new.html.erb
<h2>Add a Review for the artist</h2>

<%= form_tag artist_reviews_path, :method => :post do %>
  <%= label :review, :vote, 'Voto' %>
  <%= select :review, :vote, [1,2,3,4,5,6,7,8,9,10] %>
  <br/>
  <%= label :review, :comments, 'Recensione' %>
  <%= text_field :review, :comments %>
  <br/><br/>
  <%= submit_tag 'Aggiungi Recensione' %>
  <br>
<% end %>